### PR TITLE
convert org mode docs to markdown [WIP]

### PR DESCRIPTION
**Pull request by jgarte**
This PR is related to #226 and is the output of the following command run in each subdirectory:

```
for f in *.org; do pandoc "$f" -s -o "${f%.org}.md"; done
```

I also `git rm` the org files.

### CODE REVIEW

**Comment by lapp0** [comment]
Thanks for tackling this. `pandoc` will be a good start.

Don't bother cleaning up `behavior.md`, it will be deleted. The discourse post conversion failures can be ignored as well.

**Comment by jgarte** [comment]
> Thanks for tackling this. `pandoc` will be a good start.
> 
> Don't bother cleaning up `behavior.md`, it will be deleted. The discourse post conversion failures can be ignored as well.

I pushed an amended change that removes `behavor.org` and doesn't convert it to markdown.

**Comment by lapp0** [comment]
Fixes https://github.com/nix-gui/nix-gui/issues/217

**Comment by jgarte** [comment]
@lapp0 

Hi, what's left to do for this PR?

**Comment by lapp0** [comment]
@jgarte please fix the links, some of them still link to the old pages. For example `readme.org` links to `usage.org` instead of `usage.md`

**Comment by jgarte** [comment]
> @jgarte please fix the links, some of them still link to the old pages. For example `readme.md` links to `usage.org` instead of `usage.md`

Hi, I updated this PR just now. Sorry for the delay.

WDYT?

**Comment by lapp0** [comment]
After merging I noticed that some of the markdown isn't valid with github. For example

`{.verbatim}` tags

and

```
[*Usage*]{.spurious-link target="docs/usage.md"}
-   Development
    -   [*Development Goals*]{.spurious-link
        target="docs/development/goals.md"}
    -   [*Nix-Gui Architecture*]{.spurious-link
        target="docs/development/architecture.md"}
    -   [*Development Commands*]{.spurious-link
        target="docs/development/commands.md"}
-   [*References*]{.spurious-link target="docs/references.md"}
```

Please go over the changes and remove these invalid tags, then submite a separate pull request.

**Comment by jgarte** [comment]
> After merging I noticed that some of the markdown isn't valid with github. For example
> 
> `{.verbatim}` tags
> 
> and
> 
> ```
> [*Usage*]{.spurious-link target="docs/usage.md"}
> -   Development
>     -   [*Development Goals*]{.spurious-link
>         target="docs/development/goals.md"}
>     -   [*Nix-Gui Architecture*]{.spurious-link
>         target="docs/development/architecture.md"}
>     -   [*Development Commands*]{.spurious-link
>         target="docs/development/commands.md"}
> -   [*References*]{.spurious-link target="docs/references.md"}
> ```
> 
> Please go over the changes and remove these invalid tags, then submite a separate pull request.

@lapp0 Just looked this over now. Has this been fixed yet? If not I can work on it.

**Pull request merged**
