### PR TITLE
[WIP] Nix refactor

### PR DESCRIPTION
**Pull request by adrianparvino**

### CODE REVIEW

**Review by lapp0 — CHANGES_REQUESTED** [review]
For each nix file, could you leave a short comment on what they do?

**Comment by adrianparvino** [comment]
I reimplemented it a bit and added the documentation.

**Comment by lapp0** [comment]
lgtm. Anything else would you like to accomplish in this PR?

**Comment by adrianparvino** [comment]
Nope, this should be ready to merge.

**Comment by lapp0** [comment]
I'll take a look into fixing that, I think we can merge for now since we're not on v0.1 yet https://github.com/nix-gui/nix-gui/issues/104

**Pull request merged**
